In [3]:
# 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [7]:
# 2. Create a null vector of size 10 (★☆☆)
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
# 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [15]:
# 4. Create a vector with values ranging from 10 to 49 (★☆☆)
value_vector = np.arange(10, 50)
value_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [17]:
# 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
matrix= np.arange(0, 9).reshape((3, 3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
# 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
array = [1,2,0,0,4,0] 
nonzeros = np.nonzero(array)
nonzeros

(array([0, 1, 4], dtype=int64),)

In [25]:
# 7. Create a 3x3 identity matrix (★☆☆)
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
# 8. Create a 3x3x3 array with random values (★☆☆)
random_val = np.random.random((3,3,3))
random_val

array([[[0.79011707, 0.84638681, 0.05718695],
        [0.54185198, 0.72853544, 0.36743399],
        [0.06004025, 0.60347226, 0.87724533]],

       [[0.90767427, 0.77063626, 0.3620912 ],
        [0.97775776, 0.50703771, 0.69594281],
        [0.57506453, 0.32890577, 0.22662628]],

       [[0.29327621, 0.26885447, 0.24902164],
        [0.37740551, 0.56827259, 0.26104513],
        [0.03363957, 0.52875804, 0.95459474]]])

In [47]:
# 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
rand_val10 = np.random.random((10,10))
print(rand_val10)
print(rand_val10.min(), rand_val10.max())

[[0.17505683 0.69008883 0.9916825  0.92902577 0.78880052 0.09510216
  0.99280265 0.49494584 0.48939757 0.11872071]
 [0.34858183 0.98597802 0.14168295 0.40312601 0.14974126 0.45649047
  0.92644256 0.79417894 0.37562744 0.08743522]
 [0.02762779 0.44246508 0.8614422  0.44933199 0.5051445  0.61852937
  0.53081844 0.98687833 0.08367478 0.1748767 ]
 [0.03877727 0.32796669 0.30490198 0.36784444 0.07920757 0.77920559
  0.52219038 0.39114041 0.76968905 0.993757  ]
 [0.07899454 0.45896801 0.22272982 0.3543089  0.88898751 0.8539463
  0.96876194 0.64251901 0.35924128 0.48212591]
 [0.85925181 0.14113905 0.1395239  0.76708541 0.9647201  0.53764784
  0.81467598 0.42277939 0.45183383 0.87307958]
 [0.8921482  0.31532077 0.50640027 0.52887995 0.44438178 0.69116042
  0.25522611 0.01747413 0.09467595 0.88316419]
 [0.35123742 0.8898823  0.33097675 0.51715879 0.76278726 0.78936091
  0.24379417 0.92148311 0.06242347 0.12512856]
 [0.76066918 0.98496307 0.35463172 0.03225648 0.85851807 0.18867296
  0.04789298 

In [59]:
# 10. Create a random vector of size 30 and find the mean value (★☆☆)
vector30 = np.random.random(30)
avg = np.mean(vector30)
avg2 = vector30.mean()
print(avg2)
print(avg)

0.555755253439545
0.555755253439545


In [69]:
# 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
matrix2 = np.diag([1,2,3,4],k = -1)
matrix2

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [83]:
# 12. Normalize a 5x5 random matrix (★☆☆)
rand_val5 = np.random.rand(5,5)
rand_val5

array([[0.76362299, 0.75514523, 0.88837046, 0.53938417, 0.90164044],
       [0.45884137, 0.28675984, 0.70331356, 0.64460585, 0.98678543],
       [0.24652441, 0.55536594, 0.70751723, 0.64245393, 0.33567616],
       [0.19409799, 0.41011677, 0.35820741, 0.04633258, 0.91491617],
       [0.87253981, 0.30109282, 0.25190453, 0.17698043, 0.29155503]])

In [89]:
z_score = (rand_val5 - np.mean(rand_val5, axis = 1))/np.std(rand_val5, axis = 1)
z_score

array([[-0.04615045,  0.58876673,  2.20126368,  0.52534087,  2.08543038],
       [-2.38667948, -1.39398968,  1.15905934,  0.88277544,  2.42505387],
       [-4.01713871, -0.25693357,  1.1827336 ,  0.87546545, -0.17206887],
       [-4.41974031, -0.87179843, -0.78451107, -1.14953905,  2.13838417],
       [ 0.7902615 , -1.33331569, -1.38318817, -0.70573262, -0.34805771]])

In [93]:
# 13. How to find common values between two arrays? (★☆☆)
arr1 = [0,1,2,3,4,6]
arr2 = [2,4,6,8,]
common_nums = np.intersect1d(arr1, arr2)
common_nums

array([2, 4, 6])

In [95]:
# 14. Create a random vector of size 10 and sort it (★★☆)
vect10 = np.random.random(10)

In [101]:
vect10_sorted = np.sort(vect10)
vect10_sorted

array([0.09070597, 0.15360567, 0.22805673, 0.29948779, 0.65934824,
       0.80157566, 0.91950459, 0.94616685, 0.96432425, 0.99222492])

In [165]:
# 15. Create a second random vector of size 10 and replace the maximum value by 0 (★★☆)
vect2with10 = np.random.random(10)
vect2with10

array([0.29783876, 0.38933722, 0.98284662, 0.93809355, 0.57057951,
       0.07680165, 0.26817634, 0.82181381, 0.67892501, 0.35665365])

In [167]:
#maxi = vect2with10.max()
vect2with10[np.argmax(vect2with10)] = 0
vect2with10

array([0.29783876, 0.38933722, 0.        , 0.93809355, 0.57057951,
       0.07680165, 0.26817634, 0.82181381, 0.67892501, 0.35665365])

In [111]:
# 16. Subtract the mean of each row of a matrix (★★☆)

Help on _ArrayFunctionDispatcher in module numpy:

argmax(a, axis=None, out=None, *, keepdims=<no value>)
    Returns the indices of the maximum values along an axis.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        By default, the index is into the flattened array, otherwise
        along the specified axis.
    out : array, optional
        If provided, the result will be inserted into this array. It should
        be of the appropriate shape and dtype.
    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,
        the result will broadcast correctly against the array.
    
        .. versionadded:: 1.22.0
    
    Returns
    -------
    index_array : ndarray of ints
        Array of indices into the array. It has the same shape as `a.shape`
        with the dimension along `axis` removed. If `keepdims` is set to T